on: [workflow_dispatch, pull_request]

jobs:
  coverage-report:
    runs-on: ubuntu-latest
    name: Coverage report
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate coverage report
        id: generate-coverage-report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        uses: greentfrapp/pytest-annotate-pr@main